---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-home-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ealoltm/k8s-gitops.git
    targetRevision: main
    path: clusters/home-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
